baseURL = "https://cis1880.org/"
languageCode = "en-us"
title = "CIS 1880: DevOps"
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Schedule"
url = "/lectures/"
weight = 2

[[menu.main]]
name = "Syllabus"
url = "/syllabus/"
weight = 3
 
[[menu.main]]
name = "Resources"
url = "/resources/"
weight = 3.5

[[menu.main]]
name = "Staff"
url = "/staff/"
weight = 4

[[menu.main]]
name = "Gradescope"
url = "https://www.gradescope.com/courses/440729"
weight = 5

[markup]
  [markup.highlight]
    style = "monokailight"
[params]
  colortheme = "white"
  logo = "img/logo.png"
